/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "livekit_metrics.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LIVEKIT_METRICS_BATCH, livekit_metrics_batch_t, AUTO)


PB_BIND(LIVEKIT_TIME_SERIES_METRIC, livekit_time_series_metric_t, AUTO)


PB_BIND(LIVEKIT_METRIC_SAMPLE, livekit_metric_sample_t, AUTO)


PB_BIND(LIVEKIT_EVENT_METRIC, livekit_event_metric_t, AUTO)





