/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "livekit_models.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LIVEKIT_PAGINATION, livekit_pagination_t, AUTO)


PB_BIND(LIVEKIT_LIST_UPDATE, livekit_list_update_t, AUTO)


PB_BIND(LIVEKIT_ROOM, livekit_room_t, AUTO)


PB_BIND(LIVEKIT_CODEC, livekit_codec_t, AUTO)


PB_BIND(LIVEKIT_PLAYOUT_DELAY, livekit_playout_delay_t, AUTO)


PB_BIND(LIVEKIT_PARTICIPANT_PERMISSION, livekit_participant_permission_t, AUTO)


PB_BIND(LIVEKIT_PARTICIPANT_INFO, livekit_participant_info_t, AUTO)


PB_BIND(LIVEKIT_ENCRYPTION, livekit_encryption_t, AUTO)


PB_BIND(LIVEKIT_SIMULCAST_CODEC_INFO, livekit_simulcast_codec_info_t, AUTO)


PB_BIND(LIVEKIT_TRACK_INFO, livekit_track_info_t, AUTO)


PB_BIND(LIVEKIT_VIDEO_LAYER, livekit_video_layer_t, AUTO)


PB_BIND(LIVEKIT_DATA_PACKET, livekit_data_packet_t, AUTO)


PB_BIND(LIVEKIT_ACTIVE_SPEAKER_UPDATE, livekit_active_speaker_update_t, AUTO)


PB_BIND(LIVEKIT_SPEAKER_INFO, livekit_speaker_info_t, AUTO)


PB_BIND(LIVEKIT_USER_PACKET, livekit_user_packet_t, AUTO)


PB_BIND(LIVEKIT_SIP_DTMF, livekit_sip_dtmf_t, AUTO)


PB_BIND(LIVEKIT_TRANSCRIPTION, livekit_transcription_t, AUTO)


PB_BIND(LIVEKIT_TRANSCRIPTION_SEGMENT, livekit_transcription_segment_t, AUTO)


PB_BIND(LIVEKIT_CHAT_MESSAGE, livekit_chat_message_t, AUTO)


PB_BIND(LIVEKIT_RPC_REQUEST, livekit_rpc_request_t, AUTO)


PB_BIND(LIVEKIT_RPC_ACK, livekit_rpc_ack_t, AUTO)


PB_BIND(LIVEKIT_RPC_RESPONSE, livekit_rpc_response_t, AUTO)


PB_BIND(LIVEKIT_RPC_ERROR, livekit_rpc_error_t, AUTO)


PB_BIND(LIVEKIT_PARTICIPANT_TRACKS, livekit_participant_tracks_t, AUTO)


PB_BIND(LIVEKIT_SERVER_INFO, livekit_server_info_t, AUTO)


PB_BIND(LIVEKIT_CLIENT_INFO, livekit_client_info_t, AUTO)


PB_BIND(LIVEKIT_CLIENT_CONFIGURATION, livekit_client_configuration_t, AUTO)


PB_BIND(LIVEKIT_VIDEO_CONFIGURATION, livekit_video_configuration_t, AUTO)


PB_BIND(LIVEKIT_DISABLED_CODECS, livekit_disabled_codecs_t, AUTO)


PB_BIND(LIVEKIT_RTP_DRIFT, livekit_rtp_drift_t, AUTO)


PB_BIND(LIVEKIT_RTP_STATS, livekit_rtp_stats_t, 2)


PB_BIND(LIVEKIT_RTP_STATS_GAP_HISTOGRAM_ENTRY, livekit_rtp_stats_gap_histogram_entry_t, AUTO)


PB_BIND(LIVEKIT_RTCP_SENDER_REPORT_STATE, livekit_rtcp_sender_report_state_t, AUTO)


PB_BIND(LIVEKIT_RTP_FORWARDER_STATE, livekit_rtp_forwarder_state_t, AUTO)


PB_BIND(LIVEKIT_RTP_MUNGER_STATE, livekit_rtp_munger_state_t, AUTO)


PB_BIND(LIVEKIT_VP8_MUNGER_STATE, livekit_vp8_munger_state_t, AUTO)


PB_BIND(LIVEKIT_TIMED_VERSION, livekit_timed_version_t, AUTO)


PB_BIND(LIVEKIT_DATA_STREAM, livekit_data_stream_t, AUTO)


PB_BIND(LIVEKIT_DATA_STREAM_TEXT_HEADER, livekit_data_stream_text_header_t, AUTO)


PB_BIND(LIVEKIT_DATA_STREAM_BYTE_HEADER, livekit_data_stream_byte_header_t, AUTO)


PB_BIND(LIVEKIT_DATA_STREAM_HEADER, livekit_data_stream_header_t, AUTO)


PB_BIND(LIVEKIT_DATA_STREAM_HEADER_ATTRIBUTES_ENTRY, livekit_data_stream_header_attributes_entry_t, AUTO)


PB_BIND(LIVEKIT_DATA_STREAM_CHUNK, livekit_data_stream_chunk_t, AUTO)


PB_BIND(LIVEKIT_DATA_STREAM_TRAILER, livekit_data_stream_trailer_t, AUTO)


PB_BIND(LIVEKIT_DATA_STREAM_TRAILER_ATTRIBUTES_ENTRY, livekit_data_stream_trailer_attributes_entry_t, AUTO)


PB_BIND(LIVEKIT_WEBHOOK_CONFIG, livekit_webhook_config_t, AUTO)













































#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

