version: "3"

vars:
  INDENT: 4
  REL_PATH: "{{ relPath .USER_WORKING_DIR .ROOT_DIR }}"
  VENV_DIR: "venv"
  PYTHON_MAIN: '{{ joinPath "./src" "agent.py" }}'

tasks:
  help_setup_python_uv:
    cmds:
      - echo 'To setup and run locally:'
      - echo ''
      - echo '{{ indent .INDENT "cd" }} {{ .REL_PATH }}'
      - echo '{{ indent .INDENT "uv sync" }}'
      - echo '{{ indent .INDENT "uv run" }} {{ .PYTHON_MAIN }} download-files'
      - echo '{{ indent .INDENT "uv run" }} {{ .PYTHON_MAIN }} console'
      - echo ''

  install_python_uv:
    cmds:
      - uv sync
      - uv run {{ .PYTHON_MAIN }} download-files

  dev_python_uv:
    cmds:
      - uv run {{ .PYTHON_MAIN }} console

  help_setup_python_pip:
    cmds:
      - echo 'To setup and run locally:'
      - echo ''
      - echo '{{ indent .INDENT "cd" }} {{ .REL_PATH }}'
      - echo '{{ indent .INDENT "python3 -m venv" }} {{ .VENV_DIR }}'
      - platforms: [darwin, linux]
        cmd: echo '{{ indent .INDENT "source" }} {{ .VENV_DIR }}/bin/activate'
      - platforms: [windows]
        cmd: echo '{{ indent .INDENT "powershell"}} {{ .VENV_DIR }}/scripts/activate.ps1'
      - echo '{{ indent .INDENT "pip install -r requirements.txt" }}'
      - echo '{{ indent .INDENT "python3" }} {{ .PYTHON_MAIN }} download-files'
      - echo '{{ indent .INDENT "python3" }} {{ .PYTHON_MAIN }} console'
      - echo ''


  install_python_pip:
    cmds:
      - python3 -m venv {{ .VENV_DIR }}
      - platforms: [darwin, linux]
        cmd: "source {{ .VENV_DIR }}/bin/activate"
      - platforms: [windows]
        cmd: "powershell {{ .VENV_DIR }}/scripts/activate.ps1"
      - "pip install -r requirements.txt"

  dev_python_pip:
    cmds:
      - python3 {{ .PYTHON_MAIN }} console

  help_setup_node_pnpm:
    cmds:
      - echo 'To setup and run locally:'
      - echo ''
      - echo '{{ indent .INDENT "cd" }} {{ .REL_PATH }}'
      - echo '{{ indent .INDENT "pnpm install" }}'
      - echo '{{ indent .INDENT "pnpm build" }}'
      - echo '{{ indent .INDENT "pnpm dev" }}'
      - echo ''

  install_node_pnpm:
    cmds:
      - pnpm install

  dev_node_pnpm:
    cmds:
      - pnpm dev

  help_deploy_agent:
    cmds:
      - echo 'To deploy your agent to LiveKit cloud:'
      - echo ''
      - echo '{{ indent .INDENT "lk agent create" }}'
      - echo ''

