import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, Sidebar, SidebarInset, SidebarHeader, SidebarFooter } from "@/components/ui/sidebar";
import { NavLogo } from "@/components/custom/nav-logo";
import { ThemeToggle } from "@/components/custom/theme-toggle";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${publicSans.variable} antialiased`}
      >
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem
          disableTransitionOnChange={false}
          storageKey="prototyping-theme"
        >
          <SidebarProvider>
            <Sidebar collapsible="icon" className="bg-bg1">
              <SidebarHeader>
                <NavLogo />
              </SidebarHeader>
              <SidebarFooter className="h-full flex items-center justify-end p-4">
                <ThemeToggle/>
              </SidebarFooter>
            </Sidebar>
            <SidebarInset>
              {children}
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
