name: Build Examples
on:
  workflow_call: {}
  workflow_dispatch: {}
jobs:
  build-examples:
    name: Build Examples
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [esp32s3]
        idf_version: [release-v5.4, release-v5.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { submodules: recursive }
      - name: Build All
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf_version }}
          command: |
            pip install idf-build-apps
            idf-build-apps build -p ./examples --recursive --target ${{ matrix.target }}